config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_for :admins, ActiveAdmin::Devise.config

  resources :sensors do
    get :visualisation, :on=>:collection
  end

  resources :locations

  #resources :home
  get 'api' => 'api#show'


  resources :community

  resources :visualisation

  mount Thredded::Engine => '/forum'

  # below code to fix the active admin issue when table not exists in database as activeadmin tries to load every model.
  # for reference https://github.com/activeadmin/activeadmin/issues/783
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
  root :to => redirect("/DatenFuerDieStadt/index.html")

end

app/models/admin.rb
class Admin < Patron

  def decrement_invitation_limit!
    #stub functionality because devise invitation call this method to decrement the counter.
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :sensor
  validates :street,presence: true
  validates :zip,presence: true
  validates :longitude,presence: true
  validates :latitude,presence: true
  validates :altitude,presence: true
  validates :direction,presence: true
end

app/models/patron.rb
class Patron < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :confirmable,
  #        :recoverable, :rememberable, :trackable, :validatable
  # self.abstract_class = true
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  belongs_to :user, optional: true
  has_many :locations
end

app/models/user.rb
class User < Patron
  devise :invitable, :registerable, :confirmable
  has_many :sensors

  validates :name, length: { minimum: 2 }, allow_blank: true
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  layout 'blank'

  def show
    @sensors = Sensor.joins(:locations).group(:id)
    @locations = []
    @sensors.each do |s|
      @locations << { type: "Feature",
      geometry: {type: "Point", "coordinates": [s.locations.last.longitude.to_f + 0.00004,s.locations.last.latitude.to_f + 0.00003]},
      properties: {sensor_id: s.node_id, data: []}
      }
    end
    respond_to do |format|
      format.json { render :json => { type: "FeatureCollection",
      features: @locations
      }, :callback => params['callback'] }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :redirect_url
  before_action :set_mailer_host

  def set_mailer_host
    ActionMailer::Base.default_url_options[:host] = 'openair.cologne' unless Rails.env.development?
  end

  def redirect_url
    return new_patron_session_path unless patron_signed_in?
    case current_patron
      when User
        sensors_path
      when Admin
        root_path
    end
  end

end

app/controllers/community_controller.rb
class CommunityController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.name.blank?
      redirect_to edit_community_path(current_user.id)
    else
      redirect_to "/forum"
    end
  end

  def edit
    @user = current_user
  end

  def update
    if params[:user][:name].length <= 2
      redirect_to edit_community_path(current_user.id), notice: 'Der Name ist zu kurz'
    elsif User.find_by_name(params[:user][:name])
      redirect_to edit_community_path(current_user.id), notice: 'Der Name ist leider schon vergeben...'
    else
      @user = current_user
      @user.update_attributes(name: params[:user][:name])
      redirect_to "/forum"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:index, :show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    redirect_to sensors_path if params[:sensor_id].blank?
    @locations = Location.joins(:sensor).where({locations: {sensor_id: params[:sensor_id]}})
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
    @location.sensor_id = params[:sensor_id]
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_path(sensor_id: @location.sensor_id), notice: 'Der Ort wurde angelegt.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to locations_path(sensor_id: @location.sensor_id), notice: 'Der Ort wurde gespeichert' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @sensors = current_user.sensors
      @location = Location.joins(:sensor).where({locations: {id: params[:id]} }).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:street, :zip, :longitude, :latitude, :altitude, :face_street, :quiet_condition, :direction,:sensor_id)
    end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :authenticate_user!

  def index
    @sensors = current_user.sensors
  end

  def create
    Sensor.where(user_id: nil).last.update_attributes(user_id: current_user.id)
    redirect_to sensors_path()
  end

  def show
    @sensor = current_user.sensors.find_by_node_id(params[:id])
  end

  def edit
    @sensor = current_user.sensors.find_by_node_id(params[:id])
  end

  def visualisation
    #@sensor = current_user.sensors.find_by_node_id(params[:id])
    @sensors = Sensor.joins(:user).all
  end
end

app/controllers/sessions_controller.rb
# class SessionsController < ApplicationController
#
#   def after_sign_in_path_for(resource)
#     stored_location_for(resource) || redirect_url
#   end
#
# end

app/controllers/visualisation_controller.rb
class VisualisationController < ApplicationController
  def index

  end
  def show
    #@sensor = current_user.sensors.find_by_node_id(params[:id])
    @sensors = Sensor.joins(:user).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
        success: "alert-success",
        error: "alert-error",
        alert: "alert-danger",
        notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def bootstrap_glyphs_icon(flash_type)
    {
        success: "glyphicon-ok",
        error: "glyphicon-exclamation-sign",
        alert: "glyphicon-warning-sign",
        notice: "glyphicon-info-sign"
    }[flash_type.to_sym] || 'glyphicon-screenshot'
  end
end

app/helpers/devise_bootstrap_errors_helper.rb
module DeviseBootstrapErrorsHelper
  def devise_bootstrap_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="column">
      <h5>#{sentence}</h5>
      <ul class="red column flash">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/community/edit.html.erb
<div class="ui container">
  <div class="ui basic segments">
    <div class="panel panel-default panel-boundary">
      <div class="panel-heading">
        <h2>Editiere deinen Forum Namen</h2>
      </div>
      <div class="ui basic segment">
        <div class="ui form">
          <%= form_for(@user, url: community_path, html: { method: :put, role: "form" }) do |f| %>
              <div class="form-group">
                <%= "Forum Name" %>
                <%= f.text_field :name, class: "form-control" %>
              </div>

              <br>
              <%= f.submit  t('.update', :default => "Update"), class: "ui primary basic button" %>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="ui vertical stripe segment">
  <div class="ui middle aligned stackable grid container">
    <div class="row">
      <div class="eight wide column">
        <h3 class="ui header">Wofür messen wir und warum ist das relevant?</h3>
        <p>Wir alle atmen sie aber keinem ist klar, was drin ist, deswegen ist es sinnvoll zu messen,was ins der Luft ist.
        Jeder der möchte kann bei sich zuhause einen Sensor aufbauen und daten sammeln...</p>
      </div>
      <div class="six wide right floated column">
        <img src="/DatenFuerDieStadt/img/board.jpg" class="ui large bordered rounded image">
      </div>
    </div>
  </div>
</div>


<div class="ui vertical stripe quote segment">
  <div class="ui equal width stackable internally celled grid">
    <div class="center aligned row">
      <div class="column">
        <h3>Feinstaub</h3>
        <p>Messen die Stuttgarter im Projekt Lufdaten.info</p>
        <div class="ui vertical stripe segment">
          <div class="ui text container">
            <p>Es gibt schon über tausend Sensoren auf der ganzen Welt die Feinstaub messen...</p>
            <h4 class="ui horizontal header divider">
              <a href="https://luftdaten.info" class="ui button">Zum Projekt des OKLab Stuttgart</a>
            </h4>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="ui text container">
          <h3 class="ui header">NO2 Messen wir in Köln im "OpenAir" Projekt</h3>
          <p>Wir verteilen Sensoren, und wollen in Köln ein feinmaschiges Sticksoffdioxid Messnetz zu bauen... Dafür sammeln wir gerade Sensorwerte, die später in Werte umgerechnet werden sollen, die man mit offiziellen Daten vergleichen kann.</p>
          <a class="ui large button">Ich will </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/forum.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <!-- Required meta tags always come first -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="x-ua-compatible" content="ie=edge">

      <title>OpenAir</title>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
              <script src="https://unpkg.com/frappe-charts@0.0.8/dist/frappe-charts.min.iife.js"></script>

      <%= csrf_meta_tags %>

    </head>
    <body>

      <%# Beginn Menuleiste mit App Auswahl%>
    <div class="ui attached stackable inverted menu roove">
      <div class="ui dropdown icon item">
        <i class="fa-crosshairs icon"></i>
        <div class="menu">
        </div>
      </div>
      <a class="item" href="/DatenFuerDieStadt/index.html">
        <i class="fa-bookmark icon"></i> Openair
      </a>
      <a class="item" href="/sensors">
        <i class="list icon"></i>Sensoren
      </a>
      <a class="item" href="/community">
        <i class="list icon"></i>Forum
      </a>


    </div>

    <%# Beginn Main Content %>

    <div class="main-container">
      <div class="ui text container">
        <div id="flashes" class="column">
          <div class="ui column stackable middle aligned centered color grid">
            <% if flash[:notice] %>
              <div class="green column flash"><%= flash[:notice] %></div>
            <% end %>
            <% if flash[:alert] %>
              <div class="red column flash"><%= flash[:alert] %></div>
            <% end %>
          </div>
        </div>
      </div>
      <%= yield %>
    </div>

  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header"></h4>
          <div class="ui inverted link list">
            <a href="#" class="item"></a>
          </div>
        </div>
        <div class="three wide column">
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header"></h4>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</div>

    </body>
</html>

app/views/locations/index.html.erb
<div class="ui container">
  <div class="ui basic segments">
    <div class="panel panel-default panel-boundary">
      <h1 class="ui horizontal header divider">
        OpenAir Node
      </h1>

      <h1>Orte - an denen der Sensor aufgestellt wurde</h1>
      <h5>(Der oberste sollte immer der aktuelle Ort sein)</h5>
      <% unless @locations.blank? %>
      <table class="ui celled striped table">
        <thead>
          <tr>
            <th colspan="3">Liste:</th>
          </tr>
        </thead>

        <tbody>
          <% @locations.order(created_at: :desc).each do |location| %>
            <tr>
              <td><%= link_to "#{location.street}, #{location.zip} editieren", edit_location_path(location) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
      <br>

      <%= link_to 'Neuer Ort', new_location_path(sensor_id: params[:sensor_id]) %>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Editieren', edit_location_path(@location) %> |
 <br><br>
    <%= link_to 'Zurück', locations_path %>

app/views/sensors/index.html.erb
<div class="ui container">
  <div class="ui basic segments">
    <div class="panel panel-default panel-boundary">
      <h1 class="ui horizontal header divider">
        OpenAir Node
      </h1>
      <h4>Hallo <%= current_user.email %>,</h4>
    <p>hier kannst du deinen Sensor konfigurieren deine Benutzerdaten editieren oder dir die Sensor Daten ansehen:</p>
      <div class="ui basic segment">
        <% @sensors.each do |s| %>
          <div class="ui container">
            <div class="ui relaxed divided items">
              <div class="item">
                <div class="ui small image">
                  <img src="/DatenFuerDieStadt/img/board.jpg">
                </div>
                <div class="content">
                  <a class="header">Sensor</a>
                  <div class="meta">
                    <div><%= s.node_id %></div>
                  </div>
                  <%# if ssnor konfig aber kein ort: %>
                  <div class="description">
                    <%= link_to 'Ort', locations_path(sensor_id: s.id), class: "ui label" %>
                  </div>
                  <div class="extra">
                    <a href="<%= sensor_path(id: s.node_id)%>" class="ui left floated secondary button">
                      Auswertungen & MQTT
                    </a>
                    <a href="<%= edit_sensor_path(id: s.node_id) %>" class="ui right floated primary button">
                      Sensor Konfigurieren
                      <i class="right chevron icon"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <br>
        <% end %>
      </div>
      <% if @sensors.blank? %>
      <div class="ui basic segment">
        <%= form_for(Sensor.new, html: { method: :post, role: "form" }) do |f| %>
          <%= f.submit  'Neuer Sensor anlegen', class: "ui primary basic button" %>
        <%end%>
      </div>
      <% end %>
      <div class="ui basic segment"><%= link_to 'Benutzerdaten editieren', edit_user_registration_path(current_user), class: "ui primary basic button" %></div>
    </div>
  </div>
</div>

app/views/sensors/show.html.erb
<div class="ui container">
  <a href="/sensors" class="ui left floated primary button">
    Zurück zur Sensorliste
    <i class="left chevron icon"></i>
  </a>
</div>
<br>
<br>
<br>
<div class="ui container">
  <div class="ui row">
    <div class="panel panel-default panel-boundary">
      <h1 class="ui horizontal header divider">
        Auswertung
      </h1>
    </div>
  </div>
  <div class="ui basic segments">
    <div class="ui two cards">
      <div class="ui card">
        <div class="content">
          <div class="header">Temperatur</div>
          <div class="meta">
            <div class="group">Das Board wird warm und die Temperatur ist höher als die Umgebungstemperatur (Bezeichnung: temp)</div>
          </div>
          <div class="description">
            <a href="https://babeauf.nt.fh-koeln.de/scstat/diagram.php?senid=<%= @sensor.node_id %>&parvor_nr=3" target="_blank" class="ui left floated basic button">
              Temperaturkurve
            </a>
          </div>
        </div>
      </div>
      <div class="ui card">
        <div class="content">
          <div class="header">Feuchtigkeit</div>
          <div class="meta">
            <div class="group">(Bezeichnung: hum)</div>
          </div>
          <div class="description">
            <a href="https://babeauf.nt.fh-koeln.de/scstat/diagram.php?senid=<%= @sensor.node_id %>&parvor_nr=5" target="_blank" class="ui left floated basic button">
              Luftfeuchtigkeit
            </a>
          </div>
        </div>
      </div>
      <div class="ui card">
        <div class="content">
          <div class="header">Widerstand R1</div>
          <div class="meta">
            <div class="group">Zu beachten: Die Werte sind umgekehrt proportional</div>
          </div>
          <div class="description">
            <a href="https://babeauf.nt.fh-koeln.de/scstat/diagram.php?senid=<%= @sensor.node_id %>&parvor_nr=1" target="_blank" class="ui left floated basic button">
              Widerstandswert R1 ansehen
            </a>
          </div>
        </div>
      </div>
      <div class="ui card">
        <div class="content">
          <div class="header">Widerstand R2</div>
          <div class="meta">
            <div class="group">Zu beachten: Die Werte sind umgekehrt proportional</div>
          </div>
          <div class="description">
            <a href="https://babeauf.nt.fh-koeln.de/scstat/diagram.php?senid=<%= @sensor.node_id %>&parvor_nr=2" target="_blank" class="ui left floated basic button">
              Widerstandswert R2 ansehen
            </a>
          </div>
        </div>
      </div>
      <div class="ui card">
        <div class="content">
          <div class="header">Feinstaub</div>
          <div class="meta">
            <div class="group">(falls angeschlossen)</div>
          </div>
          <div class="description">
            <a href="<%= visualisation_index_url %>&parvor_nr=6" target="_blank" class="ui left floated basic button">
              PM2.5 ansehen
            </a>
          </div>
        </div>
      </div>
      <div class="ui card">
        <div class="content">
          <div class="header">Feinstaub</div>
          <div class="meta">
            <div class="group">(falls angeschlossen)</div>
          </div>
          <div class="description">
            <a href="<%= visualisation_index_url %>&parvor_nr=6" target="_blank" class="ui left floated basic button">
              PM10 ansehen
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <h4 class="ui horizontal header divider">
        MQTT
      </h4>
      <h3 class="ui header">Topic:  mw/openair/<%= @sensor.mqtt_id %></h3>
      <p>Server: babeauf.nt.fh-koeln.de Port: 2883 </p>
      <p>Username: <%= @sensor.mqtt_id %></p>
      <p>Password: <%= @sensor.mqtt_pass %></p>
    </div>
    <br><br>
  </div>
  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <h4 class="ui horizontal header divider">
        Hardware & Firmware
      </h4>
        <a href="https://github.com/OpenAirCgn/hardware" target="_blank" class="ui left floated basic button">
         Hier ist die Hardware zu finden
        </a>
         <a href="https://github.com/OpenAirCgn/firmware" target="_blank" class="ui left floated basic button">
         Hier ist die Firmware zu finden
        </a>
    </div>
    <br><br>
  </div>
</div>

app/views/sensors/visualisation.html.erb
<div class="ui container">
  <div class="ui basic segments">
    <div class="panel panel-default panel-boundary">
      <h1 class="ui horizontal header divider">
        OpenAir Node
      </h1>
      <div class="ui basic segments">
        <div class="ui two cards">
          <div class="ui card">
            <div class="content">
              <div class="header">Temperatur</div>
              <div class="meta">
                <div class="group">Das Board wird warm und die Temperatur ist höher als die Umgebungstemperatur (Bezeichnung: temp)</div>
              </div>
              <div class="description">
                <a href="<%= visualisation_url(parvor_nr: 3) %>" target="_blank" class="ui left floated basic button">
                  Temperaturkurve
                </a>
              </div>
            </div>
          </div>
          <div class="ui card">
            <div class="content">
              <div class="header">Feuchtigkeit</div>
              <div class="meta">
                <div class="group">(Bezeichnung: hum)</div>
              </div>
              <div class="description">
                <a href="%= visualisation_index_url %>&parvor_nr=5" target="_blank" class="ui left floated basic button">
                  Luftfeuchtigkeit
                </a>
              </div>
            </div>
          </div>
          <div class="ui card">
            <div class="content">
              <div class="header">Widerstand R1</div>
              <div class="meta">
                <div class="group">Zu beachten: Die Werte sind umgekehrt proportional</div>
              </div>
              <div class="description">
                <a href="<%= visualisation_index_url %>&parvor_nr=1" target="_blank" class="ui left floated basic button">
                  Widerstandswert R1 ansehen
                </a>
              </div>
            </div>
          </div>
          <div class="ui card">
            <div class="content">
              <div class="header">Widerstand R2</div>
              <div class="meta">
                <div class="group">Zu beachten: Die Werte sind umgekehrt proportional</div>
              </div>
              <div class="description">
                <a href="<%= visualisation_index_url %>&parvor_nr=2" target="_blank" class="ui left floated basic button">
                  Widerstandswert R2 ansehen
                </a>
              </div>
            </div>
          </div>
                <div class="ui card">
            <div class="content">
              <div class="header">Widerstand R1</div>
              <div class="meta">
                <div class="group">Zu beachten: Die Werte sind umgekehrt proportional</div>
              </div>
              <div class="description">
                <a href="<%= visualisation_index_url %>&parvor_nr=1" target="_blank" class="ui left floated basic button">
                  Widerstandswert R1 ansehen
                </a>
              </div>
            </div>
          </div>
          <div class="ui card">
            <div class="content">
              <div class="header">Widerstand R2</div>
              <div class="meta">
                <div class="group">Zu beachten: Die Werte sind umgekehrt proportional</div>
              </div>
              <div class="description">
                <a href="<%= visualisation_index_url %>&parvor_nr=2" target="_blank" class="ui left floated basic button">
                  Widerstandswert R2 ansehen
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <section id="sensor">
        <div class="container">
          <h3>Die </h3>
          <h5></h5>
          <% @sensors.map(&:node_id).each do |i| %>
           <div id="chart-<%= i %>"></div>
          <% end %>
      </section>
    </div>
  </div>
</div>
<style>
        #comparison-legend.rickshaw_legend {
          height: 140px;
        }
    </style>
<script type="text/javascript">


$(function() {

  var th_api = "https://babeauf.nt.fh-koeln.de/Messwerte/";

  var sensors = <%= raw @sensors.map(&:node_id) %>;

  $.each(sensors, function(index,node_id) {
    setTimeout(function(){
      $.getJSON( th_api, {
          //senid:"088565bd-b46a-4843-816b-ee1ea9253794",
          senid: node_id,
          parvor_nr: "<%= params[:parvor_nr] || 3 %>",
          period: '20d',
          dx: 80000
        },
        function( th_data ) {
            console.log(th_data)

          if (th_data["v"].length > 2) {
            var th_times= $.each(th_data["t"], function(i,v) {
              th_data["t"][i] = timeConverter(th_data["bt"] + v);
            })
            var th_values= $.each(th_data["v"], function(i,v) {
              //th_data["v"][i] = (600-v)/20;
              //th_data["v"][i] = -0.00010214 * v+ 95.734;
            })

            function timeConverter(UNIX_timestamp){
              var a = new Date(UNIX_timestamp);
              var months = ['Jan','Feb','Mär','Apr','May','Jun','Jul','Aug','Sep','Okt','Nov','Dez'];
              var year = a.getFullYear();
              var month = months[a.getMonth()];
              var date = a.getDate();
              var hour = a.getHours();
              var min = a.getMinutes();
              var sec = a.getSeconds();
              var time = date + ' ' + month + ' ' + year + ' ' + hour + ':' + min + ':' + sec ;
              return time;
            }

            let data = {
              labels: th_data["t"].reverse(),

              datasets: [
                {
                  title: "Deine Messung",
                  values: th_data["v"].reverse()
                }
              ]
            };
            var chart = new Chart({
              parent: "#chart-"+ node_id, // or a DOM element
              title: "Werte: " + node_id,
              data: data,
              type: 'line', // or 'line', 'scatter', 'pie', 'percentage'
              height: 250,
              is_series: 1,
              colors: ['#7cd6fd', 'violet', 'blue'],
              // hex-codes or these preset colors;
              // defaults (in order):
              // ['light-blue', 'blue', 'violet', 'red',
              // 'orange', 'yellow', 'green', 'light-green',
              // 'purple', 'magenta', 'grey', 'dark-grey']

              format_tooltip_x: d => (d + '').toUpperCase(),
              format_tooltip_y: d => d + ' pts'
            });
          }
        }
      );
    }, 1000);
  })
});
</script>

app/views/visualisation/index.html.erb
<div class="ui container">
  <div class="ui basic segments">
    <div class="panel panel-default panel-boundary">
      <h1 class="ui horizontal header divider">
        OpenAir Node
      </h1>
      <div class="ui basic segments">
        <div class="ui two cards">
          <div class="ui card">
            <div class="content">
              <div class="header">Temperatur</div>
              <div class="meta">
                <div class="group">Das Board wird warm und die Temperatur ist höher als die Umgebungstemperatur</div>
              </div>
              <div class="description">
                <a href="<%= visualisation_url(id: 3, parvor_nr: 3) %>" target="_blank" class="ui left floated basic button">
                  Temperaturkurve ansehen
                </a>
              </div>
            </div>
          </div>
          <div class="ui card">
            <div class="content">
              <div class="header">Feuchtigkeit</div>
              <div class="meta">
                <div class="group"></div>
              </div>
              <div class="description">
                <a href="<%=  visualisation_url(id: 5, parvor_nr: 5) %>" target="_blank" class="ui left floated basic button">
                  Luftfeuchtigkeitswerte ansehen
                </a>
              </div>
            </div>
          </div>
          <div class="ui card">
            <div class="content">
              <div class="header">Widerstand R1</div>
              <div class="meta">
                <div class="group">Zu beachten: Die Werte sind umgekehrt proportional zur NO2 Konzentration </div>
              </div>
              <div class="description">
                <a href="<%= visualisation_url(id: 2, parvor_nr: 1) %>" target="_blank" class="ui left floated basic button">
                  Widerstandswerte R1 ansehen
                </a>
              </div>
            </div>
          </div>
          <div class="ui card">
            <div class="content">
              <div class="header">Widerstand R2</div>
              <div class="meta">
                <div class="group">Zu beachten: Die Werte sind umgekehrt proportional zur NO2 Konzentration</div>
              </div>
              <div class="description">
                <a href="<%=  visualisation_url(id: 3, parvor_nr: 2) %>" target="_blank" class="ui left floated basic button">
                  Widerstandswerte R2 ansehen
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>